### ISSUE TITLE
"Not equal" not rendering

### ISSUE THREAD

**Issue by cajoek** [CurriculumAssociates/canvas-latex#12]
Hi,
I know that you say that everything is not supported yet but everything I have tried works except for the not equals sign.
Would it be possible for you to fix that?

Thanks!

**Comment by mattbargar-cainc** [comment]
Are you sure this isn't working? Try using the \neq symbol like so -- `4 \neq 3` -- and see what happens.

**Comment by cajoek** [comment]
Yes, it doesn't work for me at least

**Comment by cajoek** [comment]
Maybe the Katex version just needs to be updated

**Comment by cajoek** [comment]
Great, thanks! :)

**Comment by cajoek** [comment]
@ry-randall did you have time to look at it?
Thanks

**Comment by danzen** [comment]
Hi @ry-randall any luck fixing the not equal - it would be good to have.  Thanks in advance!

**Comment by danzen** [comment]
![image](https://user-images.githubusercontent.com/380281/98300173-e7cd4400-1f86-11eb-9cc5-2a71324db62e.png)  I am thinking that the / should be over top of the =.  Would that be the desired output?

**Comment by danzen** [comment]
@ry-randall 
I looked in https://katex.org/docs/supported.html#negated-relations and tried:
\\neq
\\not =
\\ne
they all give the picture above where it looks like / =
I have looked through the code in this library and could not find neq except in the canvas-latex/src/common/katex.min.js  file - so not sure where to begin to fix this.

**Comment by ry-randall** [comment]
@cajoek @danzen Thanks for your patience on this, and I apologize for my very slow response.

I just put in a note to take a look at it this weekend. That's the earliest I can get to this unfortunately.

**Comment by cajoek** [comment]
Thanks @ry-randall that would be great!
