### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by wtjcn** [CurriculumAssociates/canvas-latex#9]
npm install failed:

npm WARN tar ENOENT: no such file or directory, open '/home/xxx/canvas-latex-master/node_modules/.staging/rsvp-46ba9b32/LICENSE'
npm WARN tar ENOENT: no such file or directory, open '/home/xxx/canvas-latex-master/node_modules/.staging/create-hmac-613c5e06/index.js'
npm WARN tar ENOENT: no such file or directory, open '/home/xxx/canvas-latex-master/node_modules/.staging/pify-bc65040e/license'
npm WARN tar ENOENT: no such file or directory, open '/home/xxx/canvas-latex-master/node_modules/.staging/rsvp-46ba9b32/CHANGELOG.md'
npm WARN tar ENOENT: no such file or directory, open '/home/xxx/canvas-latex-master/node_modules/.staging/create-hmac-613c5e06/legacy.js'
npm WARN tar ENOENT: no such file or directory, open '/home/xxx/canvas-latex-master/node_modules/.staging/pify-bc65040e/readme.md'
npm WARN tar ENOENT: no such file or directory, open '/home/xxx/canvas-latex-master/node_modules/.staging/fd-slicer-9fa60c7f/LICENSE'
npm WARN tar ENOENT: no such file or directory, open '/home/xxx/canvas-latex-master/node_modules/.staging/pngjs-67291ecf/LICENSE'
npm WARN tar ENOENT: no such file or directory, open '/home/xxx/canvas-latex-master/node_modules/.staging/create-hmac-613c5e06/LICENSE'
npm WARN tar ENOENT: no such file or directory, open '/home/xxx/canvas-latex-master/node_modules/.staging/create-hmac-613c5e06/README.md'
npm WARN tar ENOENT: no such file or directory, open '/home/xxx/canvas-latex-master/node_modules/.staging/fd-slicer-9fa60c7f/index.js'
npm WARN tar ENOENT: no such file or directory, open '/home/xxx/canvas-latex-master/node_modules/.staging/promise-8598a487/lib/finally.js'
npm WARN tar ENOENT: no such file or directory, open '/home/xxx/canvas-latex-master/node_modules/.staging/promise-8598a487/lib/index.js'
npm WARN tar ENOENT: no such file or directory, open '/home/xxx/canvas-latex-master/node_modules/.staging/fd-slicer-9fa60c7f/.travis.yml'
npm WARN tar ENOENT: no such file or directory, open '/home/xxx/canvas-latex-master/node_modules/.staging/promise-8598a487/lib/node-extensions.js'
npm WARN tar ENOENT: no such file or directory, open '/home/xxx/canvas-latex-master/node_modules/.staging/fd-slicer-9fa60c7f/CHANGELOG.md'
npm WARN tar ENOENT: no such file or directory, open '/home/xxx/canvas-latex-master/node_modules/.staging/promise-8598a487/lib/rejection-tracking.js'
npm WARN tar ENOENT: no such file or directory, open '/home/xxx/canvas-latex-master/node_modules/.staging/rx-lite-6e971a2d/readme.md'
npm WARN tar ENOENT: no such file or directory, open '/home/xxx/canvas-latex-master/node_modules/.staging/promise-8598a487/lib/synchronous.js'
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/event-stream/-/event-stream-3.3.6.tgz
npm ERR! 404 
npm ERR! 404  'event-stream@3.3.6' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'canvas-latex-master'

**Comment by ry-randall** [comment]
@wtjcn Sorry for the delay on this. It's been a little while since I checked this repo.

I opened a PR with a fix here: https://github.com/CurriculumAssociates/canvas-latex/pull/10

Thanks for the heads up that this was broken 👍

**Comment by englishfarsi** [comment]
delete the node_modules folder and package-lock.json and reinstall npm.

**Comment by mattbargar-cainc** [comment]
We are working on a fix for this and should have a PR up within a few days. The current workaround is:
the node version must be downgraded to 6.11, then run `npm install`, followed upgrading the node version to 8.12.0, and running `npm install` again.  After that the repo is ready to use.

The fix will involve requiring a single, modern node/npm version.
